export const fonts = {
  MontserratThin: 'Montserrat-Thin',
  MontserratThinItalic: 'Montserrat-ThinItalic',
  MontserratSemiBoldItalic: 'Montserrat-SemiBoldItalic',
  MontserratSemiBold: 'Montserrat-SemiBold',
  MontserratRegular: 'Montserrat-Regular',
  MontserratMediumItalic: 'Montserrat-MediumItalic',
  MontserratMedium: 'Montserrat-Medium',
  MontserratLightItalic: 'Montserrat-LightItalic',
  MontserratLight: 'Montserrat-Light',
  MontserratItalic: 'Montserrat-Italic',
  MontserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
  MontserratExtraLight: 'Montserrat-ExtraLight',
  MontserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
  MontserratExtraBold: 'Montserrat-ExtraBold',
  MontserratBoldItalic: 'Montserrat-BoldItalic',
  MontserratBold: 'Montserrat-Bold',
  MontserratBlackItalic: 'Montserrat-BlackItalic',
  MontserratBlack: 'Montserrat-Black',
};
